"""
Pre-defined stock universes for Options Scanner
AUTO-GENERATED by universe_builder.py on 2026-06-13 21:09:16

CASH-SECURED-PUT (WHEEL) UNIVERSE — quality large caps across all price ranges.
Filter by capital per position using get_wheel_universe(max_capital).

Minimalist quality gate (hard filters):
- Market Cap > $10B, Price $15-600, Avg Volume > 1,000,000/day
- Positive TTM operating margin (profitable)
- Biotech / ETFs / inactive names excluded
  (D/E & Current Ratio deliberately NOT gated — unreliable for mega-caps)

Sector-aware quality score (within-sector percentile, 0-100):
- Operating margin 30% | Net margin 25% | Gross margin 20% | Liquidity 25%
Sector diversity: no sector > 35% of universe (quality-first, no forced fills).

Candidates screened: 200 | Passed gate: 188 | Final universe: 60
"""

# =============================================================================
# WHEEL STRATEGY UNIVERSE (single quality-focused universe)
# Quality stocks across all price ranges - filter by capital available
# =============================================================================

WHEEL_UNIVERSE = [
    "APP",  # AppLovin Corporation | Technology | $497 | Capital: $49.7K | Score: 94.1
    "NVDA",  # NVIDIA Corporation | Technology | $205 | Capital: $20.5K | Score: 93.8
    "META",  # Meta Platforms, Inc. | Communication Services | $567 | Capital: $56.7K | Score: 93.4
    "MCD",  # McDonald's Corporation | Consumer Cyclical | $285 | Capital: $28.5K | Score: 91.4
    "PLTR",  # Palantir Technologies Inc. | Technology | $128 | Capital: $12.8K | Score: 89.9
    "MSFT",  # Microsoft Corporation | Technology | $391 | Capital: $39.1K | Score: 89.1
    "BKNG",  # Booking Holdings Inc. | Consumer Cyclical | $165 | Capital: $16.5K | Score: 88.2
    "GOOGL",  # Alphabet Inc. | Communication Services | $360 | Capital: $36.0K | Score: 87.7
    "GOOG",  # Alphabet Inc. | Communication Services | $358 | Capital: $35.8K | Score: 87.2
    "AVGO",  # Broadcom Inc. | Technology | $382 | Capital: $38.2K | Score: 86.3
    "ADBE",  # Adobe Inc. | Technology | $204 | Capital: $20.4K | Score: 85.9
    "NEE",  # NextEra Energy, Inc. | Utilities | $86 | Capital: $8.6K | Score: 85.9
    "V",  # Visa Inc. | Financial Services | $322 | Capital: $32.2K | Score: 85.8
    "TSM",  # Taiwan Semiconductor Manufactu | Technology | $424 | Capital: $42.4K | Score: 85.6
    "KO",  # The Coca-Cola Company | Consumer Defensive | $83 | Capital: $8.3K | Score: 85.1
    "GILD",  # Gilead Sciences, Inc. | Healthcare | $126 | Capital: $12.6K | Score: 84.7
    "CME",  # CME Group Inc. | Financial Services | $270 | Capital: $27.0K | Score: 84.3
    "MA",  # Mastercard Incorporated | Financial Services | $490 | Capital: $49.0K | Score: 84.0
    "HOOD",  # Robinhood Markets, Inc. | Financial Services | $93 | Capital: $9.3K | Score: 83.5
    "AMT",  # American Tower Corporation | Real Estate | $187 | Capital: $18.7K | Score: 82.6
    "PM",  # Philip Morris International In | Consumer Defensive | $184 | Capital: $18.4K | Score: 81.5
    "AMGN",  # Amgen Inc. | Healthcare | $355 | Capital: $35.5K | Score: 79.7
    "KLAC",  # KLA Corporation | Technology | $255 | Capital: $25.5K | Score: 79.5
    "AEM",  # Agnico Eagle Mines Limited | Basic Materials | $163 | Capital: $16.3K | Score: 79.4
    "CRDO",  # Credo Technology Group Holding | Technology | $251 | Capital: $25.1K | Score: 79.0
    "SCHW",  # The Charles Schwab Corporation | Financial Services | $91 | Capital: $9.1K | Score: 78.7
    "ANET",  # Arista Networks, Inc. | Technology | $163 | Capital: $16.3K | Score: 75.8
    "NEM",  # Newmont Corporation | Basic Materials | $100 | Capital: $10.0K | Score: 75.5
    "FSLR",  # First Solar, Inc. | Energy | $267 | Capital: $26.7K | Score: 75.5
    "EOG",  # EOG Resources, Inc. | Energy | $137 | Capital: $13.7K | Score: 75.5
    "RCL",  # Royal Caribbean Cruises Ltd. | Consumer Cyclical | $294 | Capital: $29.4K | Score: 74.8
    "RDDT",  # Reddit, Inc. | Communication Services | $162 | Capital: $16.2K | Score: 74.6
    "JNJ",  # Johnson & Johnson | Healthcare | $241 | Capital: $24.1K | Score: 74.5
    "ZTS",  # Zoetis Inc. | Healthcare | $80 | Capital: $8.0K | Score: 73.9
    "UNP",  # Union Pacific Corporation | Industrials | $273 | Capital: $27.3K | Score: 73.7
    "LRCX",  # Lam Research Corporation | Technology | $367 | Capital: $36.7K | Score: 73.4
    "ISRG",  # Intuitive Surgical, Inc. | Healthcare | $411 | Capital: $41.1K | Score: 73.3
    "MRK",  # Merck & Co., Inc. | Healthcare | $119 | Capital: $11.9K | Score: 72.5
    "CSX",  # CSX Corporation | Industrials | $48 | Capital: $4.8K | Score: 72.4
    "TXN",  # Texas Instruments Incorporated | Technology | $301 | Capital: $30.1K | Score: 72.2
    "ORCL",  # Oracle Corporation | Technology | $184 | Capital: $18.4K | Score: 72.1
    "WDC",  # Western Digital Corporation | Technology | $563 | Capital: $56.3K | Score: 71.3
    "VRT",  # Vertiv Holdings Co | Industrials | $303 | Capital: $30.3K | Score: 70.1
    "AAPL",  # Apple Inc. | Technology | $291 | Capital: $29.1K | Score: 70.1
    "ADP",  # Automatic Data Processing, Inc | Industrials | $226 | Capital: $22.6K | Score: 69.8
    "INTU",  # Intuit Inc. | Technology | $277 | Capital: $27.7K | Score: 69.3
    "ADI",  # Analog Devices, Inc. | Technology | $418 | Capital: $41.8K | Score: 68.8
    "ORLY",  # O'Reilly Automotive, Inc. | Consumer Cyclical | $91 | Capital: $9.1K | Score: 68.7
    "ARM",  # Arm Holdings plc American Depo | Technology | $381 | Capital: $38.1K | Score: 68.6
    "NFLX",  # Netflix, Inc. | Communication Services | $80 | Capital: $8.0K | Score: 68.5
    "AMZN",  # Amazon.com, Inc. | Consumer Cyclical | $239 | Capital: $23.9K | Score: 68.5
    "ALAB",  # Astera Labs, Inc. Common Stock | Technology | $367 | Capital: $36.7K | Score: 68.3
    "FTNT",  # Fortinet, Inc. | Technology | $146 | Capital: $14.6K | Score: 68.0
    "AMAT",  # Applied Materials, Inc. | Technology | $567 | Capital: $56.7K | Score: 67.8
    "JPM",  # JPMorgan Chase & Co. | Financial Services | $321 | Capital: $32.1K | Score: 66.3
    "BX",  # Blackstone Inc. | Financial Services | $123 | Capital: $12.3K | Score: 66.3
    "PDD",  # PDD Holdings Inc. | Consumer Cyclical | $82 | Capital: $8.2K | Score: 66.0
    "MMM",  # 3M Company | Industrials | $158 | Capital: $15.8K | Score: 65.8
    "GE",  # GE Aerospace | Industrials | $335 | Capital: $33.5K | Score: 65.7
    "COP",  # ConocoPhillips | Energy | $117 | Capital: $11.7K | Score: 63.9
]

# Capital requirement per contract (Price x 100 for 1 CSP)
CAPITAL_REQUIREMENTS = {
    "APP": 49677,
    "NVDA": 20519,
    "META": 56698,
    "MCD": 28481,
    "PLTR": 12799,
    "MSFT": 39074,
    "BKNG": 16494,
    "GOOGL": 35968,
    "GOOG": 35816,
    "AVGO": 38207,
    "ADBE": 20402,
    "NEE": 8599,
    "V": 32239,
    "TSM": 42393,
    "KO": 8262,
    "GILD": 12559,
    "CME": 26953,
    "MA": 48998,
    "HOOD": 9319,
    "AMT": 18718,
    "PM": 18430,
    "AMGN": 35520,
    "KLAC": 25454,
    "AEM": 16264,
    "CRDO": 25081,
    "SCHW": 9110,
    "ANET": 16324,
    "NEM": 10023,
    "FSLR": 26731,
    "EOG": 13665,
    "RCL": 29438,
    "RDDT": 16210,
    "JNJ": 24087,
    "ZTS": 7957,
    "UNP": 27270,
    "LRCX": 36681,
    "ISRG": 41106,
    "MRK": 11905,
    "CSX": 4757,
    "TXN": 30112,
    "ORCL": 18413,
    "WDC": 56292,
    "VRT": 30287,
    "AAPL": 29113,
    "ADP": 22621,
    "INTU": 27673,
    "ADI": 41779,
    "ORLY": 9102,
    "ARM": 38081,
    "NFLX": 8034,
    "AMZN": 23855,
    "ALAB": 36715,
    "FTNT": 14630,
    "AMAT": 56725,
    "JPM": 32072,
    "BX": 12279,
    "PDD": 8156,
    "MMM": 15832,
    "GE": 33530,
    "COP": 11698,
}

# Per-stock metadata (company, sector, quality score, capital) for reporting.
# Consumed by earnings_monitor.py via get_stock_metadata().
STOCK_METADATA = {
    "APP": {"company": "AppLovin Corporation", "sector": "Technology", "quality_score": 94.1, "capital_required": 49677},
    "NVDA": {"company": "NVIDIA Corporation", "sector": "Technology", "quality_score": 93.8, "capital_required": 20519},
    "META": {"company": "Meta Platforms, Inc.", "sector": "Communication Services", "quality_score": 93.4, "capital_required": 56698},
    "MCD": {"company": "McDonald's Corporation", "sector": "Consumer Cyclical", "quality_score": 91.4, "capital_required": 28481},
    "PLTR": {"company": "Palantir Technologies Inc.", "sector": "Technology", "quality_score": 89.9, "capital_required": 12799},
    "MSFT": {"company": "Microsoft Corporation", "sector": "Technology", "quality_score": 89.1, "capital_required": 39074},
    "BKNG": {"company": "Booking Holdings Inc.", "sector": "Consumer Cyclical", "quality_score": 88.2, "capital_required": 16494},
    "GOOGL": {"company": "Alphabet Inc.", "sector": "Communication Services", "quality_score": 87.7, "capital_required": 35968},
    "GOOG": {"company": "Alphabet Inc.", "sector": "Communication Services", "quality_score": 87.2, "capital_required": 35816},
    "AVGO": {"company": "Broadcom Inc.", "sector": "Technology", "quality_score": 86.3, "capital_required": 38207},
    "ADBE": {"company": "Adobe Inc.", "sector": "Technology", "quality_score": 85.9, "capital_required": 20402},
    "NEE": {"company": "NextEra Energy, Inc.", "sector": "Utilities", "quality_score": 85.9, "capital_required": 8599},
    "V": {"company": "Visa Inc.", "sector": "Financial Services", "quality_score": 85.8, "capital_required": 32239},
    "TSM": {"company": "Taiwan Semiconductor Manufactu", "sector": "Technology", "quality_score": 85.6, "capital_required": 42393},
    "KO": {"company": "The Coca-Cola Company", "sector": "Consumer Defensive", "quality_score": 85.1, "capital_required": 8262},
    "GILD": {"company": "Gilead Sciences, Inc.", "sector": "Healthcare", "quality_score": 84.7, "capital_required": 12559},
    "CME": {"company": "CME Group Inc.", "sector": "Financial Services", "quality_score": 84.3, "capital_required": 26953},
    "MA": {"company": "Mastercard Incorporated", "sector": "Financial Services", "quality_score": 84.0, "capital_required": 48998},
    "HOOD": {"company": "Robinhood Markets, Inc.", "sector": "Financial Services", "quality_score": 83.5, "capital_required": 9319},
    "AMT": {"company": "American Tower Corporation", "sector": "Real Estate", "quality_score": 82.6, "capital_required": 18718},
    "PM": {"company": "Philip Morris International In", "sector": "Consumer Defensive", "quality_score": 81.5, "capital_required": 18430},
    "AMGN": {"company": "Amgen Inc.", "sector": "Healthcare", "quality_score": 79.7, "capital_required": 35520},
    "KLAC": {"company": "KLA Corporation", "sector": "Technology", "quality_score": 79.5, "capital_required": 25454},
    "AEM": {"company": "Agnico Eagle Mines Limited", "sector": "Basic Materials", "quality_score": 79.4, "capital_required": 16264},
    "CRDO": {"company": "Credo Technology Group Holding", "sector": "Technology", "quality_score": 79.0, "capital_required": 25081},
    "SCHW": {"company": "The Charles Schwab Corporation", "sector": "Financial Services", "quality_score": 78.7, "capital_required": 9110},
    "ANET": {"company": "Arista Networks, Inc.", "sector": "Technology", "quality_score": 75.8, "capital_required": 16324},
    "NEM": {"company": "Newmont Corporation", "sector": "Basic Materials", "quality_score": 75.5, "capital_required": 10023},
    "FSLR": {"company": "First Solar, Inc.", "sector": "Energy", "quality_score": 75.5, "capital_required": 26731},
    "EOG": {"company": "EOG Resources, Inc.", "sector": "Energy", "quality_score": 75.5, "capital_required": 13665},
    "RCL": {"company": "Royal Caribbean Cruises Ltd.", "sector": "Consumer Cyclical", "quality_score": 74.8, "capital_required": 29438},
    "RDDT": {"company": "Reddit, Inc.", "sector": "Communication Services", "quality_score": 74.6, "capital_required": 16210},
    "JNJ": {"company": "Johnson & Johnson", "sector": "Healthcare", "quality_score": 74.5, "capital_required": 24087},
    "ZTS": {"company": "Zoetis Inc.", "sector": "Healthcare", "quality_score": 73.9, "capital_required": 7957},
    "UNP": {"company": "Union Pacific Corporation", "sector": "Industrials", "quality_score": 73.7, "capital_required": 27270},
    "LRCX": {"company": "Lam Research Corporation", "sector": "Technology", "quality_score": 73.4, "capital_required": 36681},
    "ISRG": {"company": "Intuitive Surgical, Inc.", "sector": "Healthcare", "quality_score": 73.3, "capital_required": 41106},
    "MRK": {"company": "Merck & Co., Inc.", "sector": "Healthcare", "quality_score": 72.5, "capital_required": 11905},
    "CSX": {"company": "CSX Corporation", "sector": "Industrials", "quality_score": 72.4, "capital_required": 4757},
    "TXN": {"company": "Texas Instruments Incorporated", "sector": "Technology", "quality_score": 72.2, "capital_required": 30112},
    "ORCL": {"company": "Oracle Corporation", "sector": "Technology", "quality_score": 72.1, "capital_required": 18413},
    "WDC": {"company": "Western Digital Corporation", "sector": "Technology", "quality_score": 71.3, "capital_required": 56292},
    "VRT": {"company": "Vertiv Holdings Co", "sector": "Industrials", "quality_score": 70.1, "capital_required": 30287},
    "AAPL": {"company": "Apple Inc.", "sector": "Technology", "quality_score": 70.1, "capital_required": 29113},
    "ADP": {"company": "Automatic Data Processing, Inc", "sector": "Industrials", "quality_score": 69.8, "capital_required": 22621},
    "INTU": {"company": "Intuit Inc.", "sector": "Technology", "quality_score": 69.3, "capital_required": 27673},
    "ADI": {"company": "Analog Devices, Inc.", "sector": "Technology", "quality_score": 68.8, "capital_required": 41779},
    "ORLY": {"company": "O'Reilly Automotive, Inc.", "sector": "Consumer Cyclical", "quality_score": 68.7, "capital_required": 9102},
    "ARM": {"company": "Arm Holdings plc American Depo", "sector": "Technology", "quality_score": 68.6, "capital_required": 38081},
    "NFLX": {"company": "Netflix, Inc.", "sector": "Communication Services", "quality_score": 68.5, "capital_required": 8034},
    "AMZN": {"company": "Amazon.com, Inc.", "sector": "Consumer Cyclical", "quality_score": 68.5, "capital_required": 23855},
    "ALAB": {"company": "Astera Labs, Inc. Common Stock", "sector": "Technology", "quality_score": 68.3, "capital_required": 36715},
    "FTNT": {"company": "Fortinet, Inc.", "sector": "Technology", "quality_score": 68.0, "capital_required": 14630},
    "AMAT": {"company": "Applied Materials, Inc.", "sector": "Technology", "quality_score": 67.8, "capital_required": 56725},
    "JPM": {"company": "JPMorgan Chase & Co.", "sector": "Financial Services", "quality_score": 66.3, "capital_required": 32072},
    "BX": {"company": "Blackstone Inc.", "sector": "Financial Services", "quality_score": 66.3, "capital_required": 12279},
    "PDD": {"company": "PDD Holdings Inc.", "sector": "Consumer Cyclical", "quality_score": 66.0, "capital_required": 8156},
    "MMM": {"company": "3M Company", "sector": "Industrials", "quality_score": 65.8, "capital_required": 15832},
    "GE": {"company": "GE Aerospace", "sector": "Industrials", "quality_score": 65.7, "capital_required": 33530},
    "COP": {"company": "ConocoPhillips", "sector": "Energy", "quality_score": 63.9, "capital_required": 11698},
}

EXCLUDED_TICKERS = [
    # Biotech with pending FDA decisions (add as needed)
    # M&A targets (add as needed)
    # Delisting candidates (add as needed)
]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_wheel_universe(max_capital: int = None) -> list:
    """
    Get Wheel universe, optionally filtered by available capital.

    Args:
        max_capital: Maximum capital per position in dollars (optional)
                    e.g., 10000 filters to stocks with price <= $100

    Returns:
        List of tickers affordable within capital constraint

    Examples:
        >>> get_wheel_universe()              # All stocks
        >>> get_wheel_universe(5000)          # Stocks up to $50
        >>> get_wheel_universe(10000)         # Stocks up to $100
        >>> get_wheel_universe(25000)         # Stocks up to $250
    """
    if max_capital is None:
        return WHEEL_UNIVERSE

    return [t for t in WHEEL_UNIVERSE if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital]


def get_affordable_stocks(max_capital: int) -> list:
    """
    Get stocks affordable within capital constraint with details.

    Args:
        max_capital: Maximum capital per position in dollars

    Returns:
        List of (ticker, capital_required) tuples sorted by capital
    """
    affordable = [
        (t, CAPITAL_REQUIREMENTS[t])
        for t in WHEEL_UNIVERSE
        if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital
    ]
    return sorted(affordable, key=lambda x: x[1])


def add_to_excluded(ticker: str):
    """Add a ticker to excluded list (runtime only)"""
    if ticker not in EXCLUDED_TICKERS:
        EXCLUDED_TICKERS.append(ticker)


def format_moomoo_symbol(ticker: str) -> str:
    """Convert ticker to MooMoo format (e.g., 'AAPL' -> 'US.AAPL')"""
    if not ticker.startswith("US."):
        return f"US.{ticker}"
    return ticker


def strip_moomoo_prefix(symbol: str) -> str:
    """Convert MooMoo format to plain ticker (e.g., 'US.AAPL' -> 'AAPL')"""
    if symbol.startswith("US."):
        return symbol[3:]
    return symbol


def get_stock_metadata(ticker: str) -> dict:
    """
    Return reporting metadata for a ticker (company, sector, quality_score,
    capital_required). Falls back to safe defaults for unknown tickers so callers
    (e.g. earnings_monitor.py) never KeyError on a name outside the universe.
    """
    return STOCK_METADATA.get(ticker, {
        "company": ticker,
        "sector": "Unknown",
        "quality_score": 0.0,
        "capital_required": CAPITAL_REQUIREMENTS.get(ticker, 0),
    })
