"""
Pre-defined stock universes for Options Scanner
AUTO-GENERATED by universe_builder.py on 2026-01-30 06:34:29
Next scheduled refresh: 2026-02-13

SINGLE UNIVERSE ARCHITECTURE
Quality-ranked stocks across all price ranges. No artificial tier segmentation.
Filter by available capital per position using get_wheel_universe(max_capital).

Fundamental screening criteria:
- Market Cap >$10B
- Altman Z-Score >2.0 (bankruptcy safety)
- Piotroski Score >=5 (fundamental quality)
- Debt/Equity <1.0
- ROE >10%
- Current Ratio >1.0
- FCF Margin >2%

Quality scoring (percentile-based):
- Debt/Equity (inverse): 20% weight
- Current Ratio: 15% weight
- ROE Consistency (5yr): 15% weight
- FCF Margin: 15% weight
- Revenue Growth (3yr): 10% weight
- Gross Margin: 10% weight
- Operating Margin: 10% weight
- Volume: 5% weight

Sector diversity enforced:
- Max 3 stocks per sector
- No sector >30% of universe
- Max 2 cyclicals (Energy + Basic Materials)
- Min 4 sectors

Stocks screened: 401
Quality stocks found: 125
Final universe: 40 stocks
"""

# =============================================================================
# WHEEL STRATEGY UNIVERSE (Single Quality-Focused Universe)
# Quality stocks across all price ranges - filter by capital available
# =============================================================================

WHEEL_UNIVERSE = [
    "V",  # Visa Inc. | Financial Services | $331 | Capital: $33.1K | Score: 80.9 | Earnings: 2026-01-29
    "TSM",  # Taiwan Semiconductor Manufactu | Technology | $336 | Capital: $33.6K | Score: 80.9 | Earnings: 2026-01-29
    "KO",  # The Coca-Cola Company | Consumer Defensive | $74 | Capital: $7.4K | Score: 78.6 | Earnings: 2026-01-29
    "MSFT",  # Microsoft Corporation | Technology | $425 | Capital: $42.5K | Score: 74.6 | Earnings: 2026-01-29
    "PG",  # The Procter & Gamble Company | Consumer Defensive | $150 | Capital: $15.0K | Score: 74.2 | Earnings: 2026-01-29
    "GOOGL",  # Alphabet Inc. | Technology | $332 | Capital: $33.2K | Score: 73.5 | Earnings: 2026-01-29
    "DECK",  # Deckers Outdoor Corporation | Consumer Cyclical | $99 | Capital: $9.9K | Score: 72.6 | Earnings: 2026-01-29
    "MRK",  # Merck & Co., Inc. | Healthcare | $109 | Capital: $10.9K | Score: 70.2 | Earnings: 2026-01-29
    "SCHW",  # The Charles Schwab Corporation | Financial Services | $104 | Capital: $10.4K | Score: 68.4 | Earnings: 2026-01-29
    "EOG",  # EOG Resources, Inc. | Energy | $114 | Capital: $11.4K | Score: 67.5 | Earnings: 2026-01-29
    "ABT",  # Abbott Laboratories | Healthcare | $106 | Capital: $10.6K | Score: 66.4 | Earnings: 2026-01-29
    "BAM",  # Brookfield Asset Management Lt | Financial Services | $51 | Capital: $5.1K | Score: 66.1 | Earnings: 2026-01-29
    "MU",  # Micron Technology, Inc. | Technology | $431 | Capital: $43.1K | Score: 65.6 | Earnings: 2026-01-29
    "CRS",  # Carpenter Technology Corporati | Industrials | $321 | Capital: $32.1K | Score: 63.6 | Earnings: 2026-01-29
    "KGC",  # Kinross Gold Corporation | Basic Materials | $36 | Capital: $3.6K | Score: 63.4 | Earnings: 2026-01-29
    "AMAT",  # Applied Materials, Inc. | Technology | $336 | Capital: $33.6K | Score: 63.2 | Earnings: 2026-01-29
    "TT",  # Trane Technologies plc | Industrials | $428 | Capital: $42.8K | Score: 61.7 | Earnings: 2026-01-29
    "KVUE",  # Kenvue Inc. | Consumer Defensive | $17 | Capital: $1.7K | Score: 61.4 | Earnings: 2026-01-29
    "NFLX",  # Netflix, Inc. | Communication Services | $83 | Capital: $8.3K | Score: 61.1 | Earnings: 2026-01-29
    "NU",  # Nu Holdings Ltd. | Financial Services | $18 | Capital: $1.8K | Score: 61.1 | Earnings: 2026-01-29
    "AEM",  # Agnico Eagle Mines Limited | Basic Materials | $213 | Capital: $21.3K | Score: 60.9 | Earnings: 2026-01-29
    "DOV",  # Dover Corporation | Industrials | $201 | Capital: $20.1K | Score: 59.0 | Earnings: 2026-01-29
    "NXT",  # Nextpower Inc. | Technology | $117 | Capital: $11.7K | Score: 59.0 | Earnings: 2026-01-29
    "TXN",  # Texas Instruments Incorporated | Technology | $220 | Capital: $22.0K | Score: 57.6 | Earnings: 2026-01-29
    "DFS",  # Discover Financial Services | Financial Services | $200 | Capital: $20.0K | Score: 57.2 | Earnings: 2026-01-29
    "BSX",  # Boston Scientific Corporation | Healthcare | $92 | Capital: $9.2K | Score: 56.9 | Earnings: 2026-01-29
    "COIN",  # Coinbase Global, Inc. | Financial Services | $197 | Capital: $19.7K | Score: 56.2 | Earnings: 2026-01-29
    "SYF",  # Synchrony Financial | Financial Services | $73 | Capital: $7.3K | Score: 54.6 | Earnings: 2026-01-29
    "K",  # Kellanova | Consumer Defensive | $83 | Capital: $8.3K | Score: 53.9 | Earnings: 2026-01-29
    "JNJ",  # Johnson & Johnson | Healthcare | $227 | Capital: $22.7K | Score: 53.9 | Earnings: 2026-01-29
    "HOLX",  # Hologic, Inc. | Healthcare | $75 | Capital: $7.5K | Score: 53.8 | Earnings: 2026-01-29
    "QCOM",  # QUALCOMM Incorporated | Technology | $152 | Capital: $15.2K | Score: 53.0 | Earnings: 2026-01-29
    "BX",  # Blackstone Inc. | Financial Services | $142 | Capital: $14.2K | Score: 52.8 | Earnings: 2026-01-29
    "PYPL",  # PayPal Holdings, Inc. | Financial Services | $53 | Capital: $5.3K | Score: 51.1 | Earnings: 2026-01-29
    "INTU",  # Intuit Inc. | Technology | $497 | Capital: $49.7K | Score: 51.1 | Earnings: 2026-01-29
    "RF",  # Regions Financial Corporation | Financial Services | $28 | Capital: $2.8K | Score: 50.0 | Earnings: 2026-01-29
    "PDD",  # PDD Holdings Inc. | Consumer Cyclical | $102 | Capital: $10.2K | Score: 49.9 | Earnings: 2026-01-29
    "WMT",  # Walmart Inc. | Consumer Defensive | $117 | Capital: $11.7K | Score: 49.8 | Earnings: 2026-01-29
    "PFE",  # Pfizer Inc. | Healthcare | $26 | Capital: $2.6K | Score: 49.4 | Earnings: 2026-01-29
    "TTD",  # The Trade Desk, Inc. | Technology | $31 | Capital: $3.1K | Score: 48.1 | Earnings: 2026-01-29
]

# Capital requirement per contract (Price x 100 for 1 CSP)
CAPITAL_REQUIREMENTS = {
    "V": 33099,
    "TSM": 33591,
    "KO": 7375,
    "MSFT": 42484,
    "PG": 15001,
    "GOOGL": 33165,
    "DECK": 9858,
    "MRK": 10893,
    "SCHW": 10373,
    "EOG": 11384,
    "ABT": 10607,
    "BAM": 5072,
    "MU": 43093,
    "CRS": 32108,
    "KGC": 3624,
    "AMAT": 33589,
    "TT": 42812,
    "KVUE": 1735,
    "NFLX": 8281,
    "NU": 1847,
    "AEM": 21316,
    "DOV": 20120,
    "NXT": 11693,
    "TXN": 22007,
    "DFS": 20005,
    "BSX": 9236,
    "COIN": 19736,
    "SYF": 7339,
    "K": 8344,
    "JNJ": 22734,
    "HOLX": 7502,
    "QCOM": 15196,
    "BX": 14194,
    "PYPL": 5310,
    "INTU": 49698,
    "RF": 2823,
    "PDD": 10240,
    "WMT": 11718,
    "PFE": 2606,
    "TTD": 3140,
}

# =============================================================================
# EXCLUDED TICKERS
# [PRESERVED FROM EXISTING FILE - DO NOT MODIFY]
# =============================================================================

EXCLUDED_TICKERS = [
    # Biotech with pending FDA decisions (add as needed)
    # M&A targets (add as needed)
    # Delisting candidates (add as needed)
]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_wheel_universe(max_capital: int = None) -> list:
    """
    Get Wheel universe, optionally filtered by available capital.

    Args:
        max_capital: Maximum capital per position in dollars (optional)
                    e.g., 10000 filters to stocks with price <= $100

    Returns:
        List of tickers affordable within capital constraint

    Examples:
        >>> get_wheel_universe()              # All stocks
        >>> get_wheel_universe(5000)          # Stocks up to $50
        >>> get_wheel_universe(10000)         # Stocks up to $100
        >>> get_wheel_universe(25000)         # Stocks up to $250
    """
    if max_capital is None:
        return WHEEL_UNIVERSE

    return [t for t in WHEEL_UNIVERSE if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital]


def get_affordable_stocks(max_capital: int) -> list:
    """
    Get stocks affordable within capital constraint with details.

    Args:
        max_capital: Maximum capital per position in dollars

    Returns:
        List of (ticker, capital_required) tuples sorted by capital
    """
    affordable = [
        (t, CAPITAL_REQUIREMENTS[t])
        for t in WHEEL_UNIVERSE
        if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital
    ]
    return sorted(affordable, key=lambda x: x[1])


def add_to_excluded(ticker: str):
    """Add a ticker to excluded list (runtime only)"""
    if ticker not in EXCLUDED_TICKERS:
        EXCLUDED_TICKERS.append(ticker)


def format_moomoo_symbol(ticker: str) -> str:
    """Convert ticker to MooMoo format (e.g., 'AAPL' -> 'US.AAPL')"""
    if not ticker.startswith("US."):
        return f"US.{ticker}"
    return ticker


def strip_moomoo_prefix(symbol: str) -> str:
    """Convert MooMoo format to plain ticker (e.g., 'US.AAPL' -> 'AAPL')"""
    if symbol.startswith("US."):
        return symbol[3:]
    return symbol
