"""
Pre-defined stock universes for Options Scanner
AUTO-GENERATED by universe_builder.py on 2026-06-01 20:48:42
Next scheduled refresh: 2026-06-15

SINGLE UNIVERSE ARCHITECTURE
Quality-ranked stocks across all price ranges. No artificial tier segmentation.
Filter by available capital per position using get_wheel_universe(max_capital).

Fundamental screening criteria:
- Market Cap >$10B
- Altman Z-Score >2.0 (bankruptcy safety)
- Piotroski Score >=5 (fundamental quality)
- Debt/Equity <1.0
- ROE >10%
- Current Ratio >1.0
- FCF Margin >2%

Quality scoring (percentile-based):
- Debt/Equity (inverse): 20% weight
- Current Ratio: 15% weight
- ROE Consistency (5yr): 15% weight
- FCF Margin: 15% weight
- Revenue Growth (3yr): 10% weight
- Gross Margin: 10% weight
- Operating Margin: 10% weight
- Volume: 5% weight

Sector diversity enforced:
- Max 3 stocks per sector
- No sector >30% of universe
- Max 2 cyclicals (Energy + Basic Materials)
- Min 4 sectors

Stocks screened: 419
Quality stocks found: 148
Final universe: 50 stocks
"""

# =============================================================================
# WHEEL STRATEGY UNIVERSE (Single Quality-Focused Universe)
# Quality stocks across all price ranges - filter by capital available
# =============================================================================

WHEEL_UNIVERSE = [
    "V",  # Visa Inc. | Financial Services | $326 | Capital: $32.6K | Score: 83.8 | Earnings: 2026-06-01
    "GOOGL",  # Alphabet Inc. | Communication Services | $380 | Capital: $38.0K | Score: 83.8 | Earnings: 2026-06-01
    "MNST",  # Monster Beverage Corporation | Consumer Defensive | $88 | Capital: $8.8K | Score: 83.6 | Earnings: 2026-06-01
    "TSM",  # Taiwan Semiconductor Manufactu | Technology | $418 | Capital: $41.8K | Score: 80.7 | Earnings: 2026-06-01
    "KO",  # The Coca-Cola Company | Consumer Defensive | $79 | Capital: $7.9K | Score: 76.3 | Earnings: 2026-06-01
    "CME",  # CME Group Inc. | Financial Services | $274 | Capital: $27.4K | Score: 74.0 | Earnings: 2026-06-01
    "GILD",  # Gilead Sciences, Inc. | Healthcare | $134 | Capital: $13.4K | Score: 73.9 | Earnings: 2026-06-01
    "MSFT",  # Microsoft Corporation | Technology | $450 | Capital: $45.0K | Score: 73.3 | Earnings: 2026-06-01
    "SCHW",  # The Charles Schwab Corporation | Financial Services | $87 | Capital: $8.7K | Score: 72.2 | Earnings: 2026-06-01
    "ISRG",  # Intuitive Surgical, Inc. | Healthcare | $425 | Capital: $42.5K | Score: 72.0 | Earnings: 2026-06-01
    "DOV",  # Dover Corporation | Industrials | $211 | Capital: $21.1K | Score: 70.4 | Earnings: 2026-06-01
    "FSLR",  # First Solar, Inc. | Energy | $307 | Capital: $30.7K | Score: 69.3 | Earnings: 2026-06-01
    "AMAT",  # Applied Materials, Inc. | Technology | $450 | Capital: $45.0K | Score: 68.2 | Earnings: 2026-06-01
    "BAM",  # Brookfield Asset Management Lt | Financial Services | $49 | Capital: $4.9K | Score: 66.2 | Earnings: 2026-06-01
    "NFLX",  # Netflix, Inc. | Communication Services | $86 | Capital: $8.6K | Score: 65.2 | Earnings: 2026-06-01
    "CVNA",  # Carvana Co. | Consumer Cyclical | $73 | Capital: $7.3K | Score: 65.0 | Earnings: 2026-06-01
    "RMD",  # ResMed Inc. | Healthcare | $191 | Capital: $19.1K | Score: 64.6 | Earnings: 2026-06-01
    "VEEV",  # Veeva Systems Inc. | Healthcare | $174 | Capital: $17.4K | Score: 64.6 | Earnings: 2026-06-01
    "AEM",  # Agnico Eagle Mines Limited | Basic Materials | $183 | Capital: $18.3K | Score: 64.5 | Earnings: 2026-06-01
    "TT",  # Trane Technologies plc | Industrials | $451 | Capital: $45.1K | Score: 62.7 | Earnings: 2026-06-01
    "BTI",  # British American Tobacco p.l.c | Consumer Defensive | $62 | Capital: $6.2K | Score: 62.3 | Earnings: 2026-06-01
    "PDD",  # PDD Holdings Inc. | Consumer Cyclical | $84 | Capital: $8.4K | Score: 62.2 | Earnings: 2026-06-01
    "INTU",  # Intuit Inc. | Technology | $332 | Capital: $33.2K | Score: 61.8 | Earnings: 2026-06-01
    "SPGI",  # S&P Global Inc. | Financial Services | $424 | Capital: $42.4K | Score: 61.4 | Earnings: 2026-06-01
    "PG",  # The Procter & Gamble Company | Consumer Defensive | $144 | Capital: $14.4K | Score: 61.4 | Earnings: 2026-06-01
    "EOG",  # EOG Resources, Inc. | Energy | $133 | Capital: $13.3K | Score: 59.8 | Earnings: 2026-06-01
    "ABNB",  # Airbnb, Inc. | Consumer Cyclical | $133 | Capital: $13.3K | Score: 59.0 | Earnings: 2026-06-01
    "ACGL",  # Arch Capital Group Ltd. | Financial Services | $89 | Capital: $8.9K | Score: 57.6 | Earnings: 2026-06-01
    "HOOD",  # Robinhood Markets, Inc. | Financial Services | $94 | Capital: $9.4K | Score: 57.4 | Earnings: 2026-06-01
    "ICE",  # Intercontinental Exchange, Inc | Financial Services | $148 | Capital: $14.8K | Score: 56.4 | Earnings: 2026-06-01
    "QCOM",  # QUALCOMM Incorporated | Technology | $251 | Capital: $25.1K | Score: 55.3 | Earnings: 2026-06-01
    "TS",  # Tenaris S.A. | Energy | $61 | Capital: $6.1K | Score: 54.9 | Earnings: 2026-06-01
    "DXCM",  # DexCom, Inc. | Healthcare | $74 | Capital: $7.4K | Score: 54.8 | Earnings: 2026-06-01
    "SAP",  # SAP SE | Technology | $182 | Capital: $18.2K | Score: 54.8 | Earnings: 2026-06-01
    "KGC",  # Kinross Gold Corporation | Basic Materials | $30 | Capital: $3.0K | Score: 54.7 | Earnings: 2026-06-01
    "BX",  # Blackstone Inc. | Financial Services | $117 | Capital: $11.7K | Score: 53.4 | Earnings: 2026-06-01
    "PYPL",  # PayPal Holdings, Inc. | Financial Services | $45 | Capital: $4.5K | Score: 53.2 | Earnings: 2026-06-01
    "EW",  # Edwards Lifesciences Corporati | Healthcare | $86 | Capital: $8.6K | Score: 53.2 | Earnings: 2026-06-01
    "UL",  # Unilever PLC | Consumer Defensive | $56 | Capital: $5.6K | Score: 52.3 | Earnings: 2026-06-01
    "DFS",  # Discover Financial Services | Financial Services | $200 | Capital: $20.0K | Score: 52.2 | Earnings: 2026-06-01
    "SPOT",  # Spotify Technology S.A. | Communication Services | $498 | Capital: $49.8K | Score: 51.3 | Earnings: 2026-06-01
    "HIG",  # The Hartford Financial Service | Financial Services | $127 | Capital: $12.7K | Score: 50.8 | Earnings: 2026-06-01
    "NDAQ",  # Nasdaq, Inc. | Financial Services | $93 | Capital: $9.3K | Score: 49.8 | Earnings: 2026-06-01
    "KVUE",  # Kenvue Inc. | Consumer Defensive | $17 | Capital: $1.7K | Score: 49.3 | Earnings: 2026-06-01
    "IDXX",  # IDEXX Laboratories, Inc. | Healthcare | $564 | Capital: $56.4K | Score: 49.1 | Earnings: 2026-06-01
    "TRV",  # The Travelers Companies, Inc. | Financial Services | $292 | Capital: $29.2K | Score: 48.6 | Earnings: 2026-06-01
    "IBN",  # ICICI Bank Limited | Financial Services | $26 | Capital: $2.6K | Score: 48.1 | Earnings: 2026-06-01
    "JPM",  # JPMorgan Chase & Co. | Financial Services | $299 | Capital: $29.9K | Score: 48.0 | Earnings: 2026-06-01
    "USB",  # U.S. Bancorp | Financial Services | $55 | Capital: $5.5K | Score: 48.0 | Earnings: 2026-06-01
    "WFC",  # Wells Fargo & Company | Financial Services | $78 | Capital: $7.8K | Score: 48.0 | Earnings: 2026-06-01
]

# Capital requirement per contract (Price x 100 for 1 CSP)
CAPITAL_REQUIREMENTS = {
    "V": 32636,
    "GOOGL": 38034,
    "MNST": 8808,
    "TSM": 41845,
    "KO": 7901,
    "CME": 27354,
    "GILD": 13443,
    "MSFT": 45024,
    "SCHW": 8735,
    "ISRG": 42464,
    "DOV": 21136,
    "FSLR": 30679,
    "AMAT": 45006,
    "BAM": 4860,
    "NFLX": 8602,
    "CVNA": 7300,
    "RMD": 19057,
    "VEEV": 17432,
    "AEM": 18315,
    "TT": 45130,
    "BTI": 6179,
    "PDD": 8444,
    "INTU": 33153,
    "SPGI": 42400,
    "PG": 14357,
    "EOG": 13338,
    "ABNB": 13331,
    "ACGL": 8934,
    "HOOD": 9430,
    "ICE": 14785,
    "QCOM": 25102,
    "TS": 6093,
    "DXCM": 7373,
    "SAP": 18179,
    "KGC": 3020,
    "BX": 11699,
    "PYPL": 4475,
    "EW": 8647,
    "UL": 5645,
    "DFS": 20005,
    "SPOT": 49768,
    "HIG": 12713,
    "NDAQ": 9252,
    "KVUE": 1728,
    "IDXX": 56353,
    "TRV": 29189,
    "IBN": 2623,
    "JPM": 29931,
    "USB": 5485,
    "WFC": 7754,
}

# =============================================================================
# EXCLUDED TICKERS
# [PRESERVED FROM EXISTING FILE - DO NOT MODIFY]
# =============================================================================

# Per-stock metadata (company, sector, quality score, capital) for reporting.
# Consumed by earnings_monitor.py via get_stock_metadata().
STOCK_METADATA = {
    "V": {"company": "Visa Inc.", "sector": "Financial Services", "quality_score": 83.8, "capital_required": 32636},
    "GOOGL": {"company": "Alphabet Inc.", "sector": "Communication Services", "quality_score": 83.8, "capital_required": 38034},
    "MNST": {"company": "Monster Beverage Corporation", "sector": "Consumer Defensive", "quality_score": 83.6, "capital_required": 8808},
    "TSM": {"company": "Taiwan Semiconductor Manufactu", "sector": "Technology", "quality_score": 80.7, "capital_required": 41845},
    "KO": {"company": "The Coca-Cola Company", "sector": "Consumer Defensive", "quality_score": 76.3, "capital_required": 7901},
    "CME": {"company": "CME Group Inc.", "sector": "Financial Services", "quality_score": 74.0, "capital_required": 27354},
    "GILD": {"company": "Gilead Sciences, Inc.", "sector": "Healthcare", "quality_score": 73.9, "capital_required": 13443},
    "MSFT": {"company": "Microsoft Corporation", "sector": "Technology", "quality_score": 73.3, "capital_required": 45024},
    "SCHW": {"company": "The Charles Schwab Corporation", "sector": "Financial Services", "quality_score": 72.2, "capital_required": 8735},
    "ISRG": {"company": "Intuitive Surgical, Inc.", "sector": "Healthcare", "quality_score": 72.0, "capital_required": 42464},
    "DOV": {"company": "Dover Corporation", "sector": "Industrials", "quality_score": 70.4, "capital_required": 21136},
    "FSLR": {"company": "First Solar, Inc.", "sector": "Energy", "quality_score": 69.3, "capital_required": 30679},
    "AMAT": {"company": "Applied Materials, Inc.", "sector": "Technology", "quality_score": 68.2, "capital_required": 45006},
    "BAM": {"company": "Brookfield Asset Management Lt", "sector": "Financial Services", "quality_score": 66.2, "capital_required": 4860},
    "NFLX": {"company": "Netflix, Inc.", "sector": "Communication Services", "quality_score": 65.2, "capital_required": 8602},
    "CVNA": {"company": "Carvana Co.", "sector": "Consumer Cyclical", "quality_score": 65.0, "capital_required": 7300},
    "RMD": {"company": "ResMed Inc.", "sector": "Healthcare", "quality_score": 64.6, "capital_required": 19057},
    "VEEV": {"company": "Veeva Systems Inc.", "sector": "Healthcare", "quality_score": 64.6, "capital_required": 17432},
    "AEM": {"company": "Agnico Eagle Mines Limited", "sector": "Basic Materials", "quality_score": 64.5, "capital_required": 18315},
    "TT": {"company": "Trane Technologies plc", "sector": "Industrials", "quality_score": 62.7, "capital_required": 45130},
    "BTI": {"company": "British American Tobacco p.l.c", "sector": "Consumer Defensive", "quality_score": 62.3, "capital_required": 6179},
    "PDD": {"company": "PDD Holdings Inc.", "sector": "Consumer Cyclical", "quality_score": 62.2, "capital_required": 8444},
    "INTU": {"company": "Intuit Inc.", "sector": "Technology", "quality_score": 61.8, "capital_required": 33153},
    "SPGI": {"company": "S&P Global Inc.", "sector": "Financial Services", "quality_score": 61.4, "capital_required": 42400},
    "PG": {"company": "The Procter & Gamble Company", "sector": "Consumer Defensive", "quality_score": 61.4, "capital_required": 14357},
    "EOG": {"company": "EOG Resources, Inc.", "sector": "Energy", "quality_score": 59.8, "capital_required": 13338},
    "ABNB": {"company": "Airbnb, Inc.", "sector": "Consumer Cyclical", "quality_score": 59.0, "capital_required": 13331},
    "ACGL": {"company": "Arch Capital Group Ltd.", "sector": "Financial Services", "quality_score": 57.6, "capital_required": 8934},
    "HOOD": {"company": "Robinhood Markets, Inc.", "sector": "Financial Services", "quality_score": 57.4, "capital_required": 9430},
    "ICE": {"company": "Intercontinental Exchange, Inc", "sector": "Financial Services", "quality_score": 56.4, "capital_required": 14785},
    "QCOM": {"company": "QUALCOMM Incorporated", "sector": "Technology", "quality_score": 55.3, "capital_required": 25102},
    "TS": {"company": "Tenaris S.A.", "sector": "Energy", "quality_score": 54.9, "capital_required": 6093},
    "DXCM": {"company": "DexCom, Inc.", "sector": "Healthcare", "quality_score": 54.8, "capital_required": 7373},
    "SAP": {"company": "SAP SE", "sector": "Technology", "quality_score": 54.8, "capital_required": 18179},
    "KGC": {"company": "Kinross Gold Corporation", "sector": "Basic Materials", "quality_score": 54.7, "capital_required": 3020},
    "BX": {"company": "Blackstone Inc.", "sector": "Financial Services", "quality_score": 53.4, "capital_required": 11699},
    "PYPL": {"company": "PayPal Holdings, Inc.", "sector": "Financial Services", "quality_score": 53.2, "capital_required": 4475},
    "EW": {"company": "Edwards Lifesciences Corporati", "sector": "Healthcare", "quality_score": 53.2, "capital_required": 8647},
    "UL": {"company": "Unilever PLC", "sector": "Consumer Defensive", "quality_score": 52.3, "capital_required": 5645},
    "DFS": {"company": "Discover Financial Services", "sector": "Financial Services", "quality_score": 52.2, "capital_required": 20005},
    "SPOT": {"company": "Spotify Technology S.A.", "sector": "Communication Services", "quality_score": 51.3, "capital_required": 49768},
    "HIG": {"company": "The Hartford Financial Service", "sector": "Financial Services", "quality_score": 50.8, "capital_required": 12713},
    "NDAQ": {"company": "Nasdaq, Inc.", "sector": "Financial Services", "quality_score": 49.8, "capital_required": 9252},
    "KVUE": {"company": "Kenvue Inc.", "sector": "Consumer Defensive", "quality_score": 49.3, "capital_required": 1728},
    "IDXX": {"company": "IDEXX Laboratories, Inc.", "sector": "Healthcare", "quality_score": 49.1, "capital_required": 56353},
    "TRV": {"company": "The Travelers Companies, Inc.", "sector": "Financial Services", "quality_score": 48.6, "capital_required": 29189},
    "IBN": {"company": "ICICI Bank Limited", "sector": "Financial Services", "quality_score": 48.1, "capital_required": 2623},
    "JPM": {"company": "JPMorgan Chase & Co.", "sector": "Financial Services", "quality_score": 48.0, "capital_required": 29931},
    "USB": {"company": "U.S. Bancorp", "sector": "Financial Services", "quality_score": 48.0, "capital_required": 5485},
    "WFC": {"company": "Wells Fargo & Company", "sector": "Financial Services", "quality_score": 48.0, "capital_required": 7754},
}

EXCLUDED_TICKERS = [
    # Biotech with pending FDA decisions (add as needed)
    # M&A targets (add as needed)
    # Delisting candidates (add as needed)
]


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_wheel_universe(max_capital: int = None) -> list:
    """
    Get Wheel universe, optionally filtered by available capital.

    Args:
        max_capital: Maximum capital per position in dollars (optional)
                    e.g., 10000 filters to stocks with price <= $100

    Returns:
        List of tickers affordable within capital constraint

    Examples:
        >>> get_wheel_universe()              # All stocks
        >>> get_wheel_universe(5000)          # Stocks up to $50
        >>> get_wheel_universe(10000)         # Stocks up to $100
        >>> get_wheel_universe(25000)         # Stocks up to $250
    """
    if max_capital is None:
        return WHEEL_UNIVERSE

    return [t for t in WHEEL_UNIVERSE if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital]


def get_affordable_stocks(max_capital: int) -> list:
    """
    Get stocks affordable within capital constraint with details.

    Args:
        max_capital: Maximum capital per position in dollars

    Returns:
        List of (ticker, capital_required) tuples sorted by capital
    """
    affordable = [
        (t, CAPITAL_REQUIREMENTS[t])
        for t in WHEEL_UNIVERSE
        if CAPITAL_REQUIREMENTS.get(t, 0) <= max_capital
    ]
    return sorted(affordable, key=lambda x: x[1])


def add_to_excluded(ticker: str):
    """Add a ticker to excluded list (runtime only)"""
    if ticker not in EXCLUDED_TICKERS:
        EXCLUDED_TICKERS.append(ticker)


def format_moomoo_symbol(ticker: str) -> str:
    """Convert ticker to MooMoo format (e.g., 'AAPL' -> 'US.AAPL')"""
    if not ticker.startswith("US."):
        return f"US.{ticker}"
    return ticker


def strip_moomoo_prefix(symbol: str) -> str:
    """Convert MooMoo format to plain ticker (e.g., 'US.AAPL' -> 'AAPL')"""
    if symbol.startswith("US."):
        return symbol[3:]
    return symbol


def get_stock_metadata(ticker: str) -> dict:
    """
    Return reporting metadata for a ticker (company, sector, quality_score,
    capital_required). Falls back to safe defaults for unknown tickers so callers
    (e.g. earnings_monitor.py) never KeyError on a name outside the universe.
    """
    return STOCK_METADATA.get(ticker, {
        "company": ticker,
        "sector": "Unknown",
        "quality_score": 0.0,
        "capital_required": CAPITAL_REQUIREMENTS.get(ticker, 0),
    })
